query findAddressById($id: ID!) {
  getAddressById(id: $id) {
    id
    addressLine1
    addressLine2
    addressType
    city
    countryId
    stateId
    deliveryNum
    name
    postalCode
    deliveryInstructions
  }
}

query findAllAddresses(
  $page: Int = 1
  $limit: Int = 25
  $name: String = ""
  $addressType: AddressTypeEnum
) {
  getAllAddresses(
    page: $page
    limit: $limit
    name: $name
    addressType: $addressType
  ) {
    addresses {
      id
      addressLine1
      addressLine2
      addressType
      city
      countryId
      stateId
      deliveryNum
      name
      postalCode
      deliveryInstructions
    }
    total
    hasMore
  }
}
