mutation createAddress($input: CreateAddressInput!) {
  createAddress(input: $input) {
    id
    addressLine1
    addressLine2
    addressType
    city
    countryId
    stateId
    deliveryNum
    name
    postalCode
    deliveryInstructions
  }
}

mutation updateAddress($id: ID!, $input: UpdateAddressInput!) {
  updateAddress(id: $id, input: $input) {
    id
    addressLine1
    addressLine2
    addressType
    city
    countryId
    stateId
    deliveryNum
    name
    postalCode
    deliveryInstructions
  }
}

mutation deleteAddress($id: ID!) {
  deleteAddress(id: $id) {
    id
    name
  }
}
