query findAllMovements(
  $warehouseId: ID!
  $page: Int
  $limit: Int
  $variantId: ID
  $createdById: ID
  $dateFrom: DateTime
  $dateTo: DateTime
  $includeDeleted: Boolean
  $sortBy: SortBy
  $sortOrder: SortOrder
) {
  getAllStockMovements(
    warehouseId: $warehouseId
    page: $page
    limit: $limit
    variantId: $variantId
    createdById: $createdById
    dateFrom: $dateFrom
    dateTo: $dateTo
    includeDeleted: $includeDeleted
    sortBy: $sortBy
    sortOrder: $sortOrder
  ) {
    stockMovements {
      id
      warehouseId
      deltaQty
      reason
      occurredAt
      productName
      variantSku
      variantFirstAttribute {
        key
        value
      }
    }
    total
    hasMore
  }
}
