mutation createCategory($input: CreateCategoryInput!) {
  createCategory(input: $input) {
    id
    name
    description
    cover
    subCategories {
      id
      cover
      description
      name
    }
  }
}

mutation updateCategory($id: ID!, $input: UpdateCategoryInput!) {
  updateCategory(id: $id, input: $input) {
    id
    name
    description
    cover
    subCategories {
      id
      name
      description
      cover
      subCategories {
        id
        name
        description
        cover
      }
    }
  }
}

mutation delete($id: ID!) {
  deleteCategory(id: $id) {
    name
  }
}
