query findTenantProfile {
  getTenantById {
    ownerName
    email
    businessName
    description
    domain
    logo
    defaultPhoneNumberId
  }
}

query findTenantAuthInfo {
  getTenantById {
    ownerName
    businessName
    logo
  }
}
