query findProductById($id: String!) {
  getProductById(id: $id) {
    id
    name
    shortDescription
    longDescription
    cover
    brand
    manufacturer
    tags
    media {
      mediaType
      position
      url
    }
    categories {
      categoryId
      categoryName
    }
    variants {
      id
      price
      condition
      attributes {
        key
        value
      }
      weight
      dimension {
        height
        width
        length
      }
      sku
      ean
      upc
      isbn
      barcode
      variantCover
      variantMedia {
        mediaType
        url
        position
        variantId
        productId
      }
      warranties {
        coverage
        instructions
        months
      }
      installmentPayments {
        interestRate
        months
      }
      personalizationOptions
    }
    sustainabilities {
      certification
      recycledPercentage
    }
    updatedAt
    createdAt
    productType
    isArchived
  }
}

query findAllProducts(
  $page: Float = 1
  $limit: Float = 25
  $categoriesIds: [ID!] = []
  $type: TypeEnum
  $sortBy: SortBy = NAME
  $sortOrder: SortOrder = ASC
  $includeSoftDeleted: Boolean = false
  $name: String = ""
) {
  getAllProducts(
    page: $page
    limit: $limit
    categoriesIds: $categoriesIds
    type: $type
    sortBy: $sortBy
    sortOrder: $sortOrder
    includeSoftDeleted: $includeSoftDeleted
    name: $name
  ) {
    products {
      id
      name
      brand
      categories {
        categoryId
        categoryName
      }
      cover
      createdAt
      longDescription
      manufacturer
      media {
        mediaType
        position
        productId
        url
        variantId
      }
      isArchived
      productType
      shortDescription
      sustainabilities {
        certification
        recycledPercentage
      }
      tags
      updatedAt
      variants {
        id
        attributes {
          key
          value
        }
        barcode
        condition
        dimension {
          height
          length
          width
        }
        ean
        installmentPayments {
          interestRate
          months
        }
        isbn
        personalizationOptions
        price
        sku
        upc
        variantCover
        variantMedia {
          mediaType
          position
          productId
          url
          variantId
        }
        warranties {
          coverage
          instructions
          months
        }
        weight
        isArchived
      }
    }
    total
    hasMore
  }
}

query findAllVariantsToCreateStock(
  $page: Float = 1
  $limit: Float = 10
  $sortBy: SortBy = NAME
  $sortOrder: SortOrder = ASC
  $includeSoftDeleted: Boolean = false
  $name: String = ""
) {
  getAllProducts(
    page: $page
    limit: $limit
    sortBy: $sortBy
    sortOrder: $sortOrder
    includeSoftDeleted: $includeSoftDeleted
    name: $name
  ) {
    products {
      name
      variants {
        id
        attributes {
          key
          value
        }
        sku
      }
    }
    total
    hasMore
  }
}
