import type { Meta, StoryObj } from '@storybook/react';
import MainLanding from '@organisms/landing/MainLanding';
import { NextIntlClientProvider } from 'next-intl';

const messages = {
  Landing: {
    buttonStartFree: 'Start Free',
    buttonViewPlans: 'View plans',
    login: 'Log in',
    pricing: 'Pricing',
    title: 'Grow Your Brand Effortlessly with EasyStore',
    slogan:
      'Build a powerful online store that adapts to any business \u2013 no coding or developer needed!',
    starting: 'Starting to sell is very easy',
    addYourProducts: 'Add your products',
    customizeYourStore: 'Customize your store',
    setUpdPayments: 'Set up payments',
    community: 'Community',
    termsConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    inc: '\u00a9 2025 EasyStore, Inc. All rights reserved',
    unlimetedProductsT: 'Unlimited products',
    unlimetedProducts: 'Add as many products as you like',
    customDomainsT: 'Custom domains',
    customDomains: 'Use your own domain or get a free one',
    paymantT: 'Payment gateways',
    paymant: 'Choose the payment gateways that you need',
    growBussinessT: 'Grow your business',
    growBussiness:
      'Use data-driven insights to optimize your store and boost sales',
    zeroTransactionT: 'Zero transaction fees',
    zeroTransaction: 'We don\u2019t charge commission on sales',
    manageEaseT: 'Manage with ease',
    manageEase: 'Easily track orders, manage inventory, and fulfill orders',
    noCodeT: 'No code setup',
    noCode: 'Create a store in minutes with our intuitive dashboard',
    sellEverywhereT: 'Sell everywhere',
    sellEverywhere: 'Reach customers on social media, marketplaces, and more',
    searchEngineT: 'Search Engine Optimization',
    searchEngine: 'Attract more organic traffic and reach new customers',
    inventorySyncT: 'Inventory Synchronization',
    inventorySync:
      'Automatically sync your inventory across your online and in-person stores',
    featureTitle: 'Why choose EasyStore?',
    featureText:
      'EasyStore is the all-in-one solution for growing businesses. Our platform includes everything you need to start, run, and scale your online business.',
    everyWhereTitle: 'Manage your business from anywhere',
    everyWhereText: 'Desktop and mobile',
    whatIsEasyStoreTitle: 'What is EasyStore and how does it work?',
    whatIsEasyStore:
      'EasyStore is an all-in-one commerce platform built for independent business owners to start, run, and grow their businesses online, in-store, and everywhere in between.',
    EasyStoreCostTitle: 'How much does EasyStore cost?',
    EasyStoreCost:
      'You can try EasyStore premium free for 14 days, no credit card required.',
    cancelAccountTitle: 'Can I cancel my account at any time?',
    cancelAccount: 'Yes, cancel anytime. Annual plans end at term.',
    changePlanTitle: 'Can I change my plan later on?',
    changePlan: 'Upgrade or downgrade at any time.',
    dicountsTitle: 'Do you offer any discounts?',
    dicounts: '25% off yearly on most plans.',
    countriesUseTitle: 'In what countries can I use EasyStore?',
    countriesUse: 'Currently in Guatemala; expanding soon.',
    transactionTitle: 'Are there transaction fees?',
    transaction: 'No, there are no transaction fees.',
    switchToEasyStoreTitle:
      "I'm looking to switch to EasyStore. How do I get my data over?",
    switchToEasyStore: 'On Premium and above, we help you migrate.',
    domainNameTitle: 'Can I use my own domain name with EasyStore?',
    domainName: 'Yes, bring your domain or get one here.',
    hostingTitle: 'Do I get free web hosting when I open an online store?',
    hosting: 'Hosting included on all plans.',
    onlineStoreTitle: 'Does my online store integrate with my in person store?',
    onlineStore: 'Yes, inventory and payments sync automatically.',
    FAQsTitle: 'Frequently asked questions',
    aboutTitle: 'About us',
    aboutText1: 'We empower entrepreneurs to go online easily.',
    aboutText2: 'Accessible e\u2011commerce for all with great tools.',
    aboutText3: 'Built by a passionate team focused on simplicity.',
    foundedT: 'Founded',
    founded: '2025 \u2013 supporting the future of commerce',
    managedT: 'Managed By',
    managed: 'Engineers with a vision for accessible tech',
    headquartersT: 'Headquarters',
    headquarters: 'Guatemala City \u2014 global mindset',
    focusT: 'Focus',
    focus: 'Fast setup, beautiful design, and no\u2011code simplicity',
    missionT: 'Mission',
    mission: 'Help businesses sell online without limits',
    'pricing&Plans': 'Plans & Pricing',
    pricingTitle: 'Select the Ideal Plan for Your Business',
    pricingDescription:
      'Discover cost\u2011effective plans packed with features to grow sales.',
  },
  ConfirmRegister: {
    month: 'month',
    yearly: 'yearly',
    from: 'from',
    basic: 'Basic',
    premium: 'Premium',
    advanced: 'Advanced',
    enterprise: 'Enterprise',
    buttonBasic: 'Choose Basic',
    buttonPremium: 'Choose Premium',
    buttonAdvanced: 'Choose Advanced',
    buttonEnterprise: 'Contact Sales',
    '1featureBasic': 'Basic feature 1',
    '2featureBasic': 'Basic feature 2',
    '3featureBasic': 'Basic feature 3',
    '4featureBasic': 'Basic feature 4',
    '5featureBasic': 'Basic feature 5',
    '6featureBasic': 'Basic feature 6',
    '7featureBasic': 'Basic feature 7',
    '8featureBasic': 'Basic feature 8',
    '9featureBasic': 'Basic feature 9',
    '10featureBasic': 'Basic feature 10',
    '1featurePremium': 'Premium feature 1',
    '2featurePremium': 'Premium feature 2',
    '3featurePremium': 'Premium feature 3',
    '4featurePremium': 'Premium feature 4',
    '5featurePremium': 'Premium feature 5',
    '6featurePremium': 'Premium feature 6',
    '7featurePremium': 'Premium feature 7',
    '8featurePremium': 'Premium feature 8',
    '9featurePremium': 'Premium feature 9',
    '10featurePremium': 'Premium feature 10',
    '1featureAdvanced': 'Advanced feature 1',
    '2featureAdvanced': 'Advanced feature 2',
    '3featureAdvanced': 'Advanced feature 3',
    '4featureAdvanced': 'Advanced feature 4',
    '5featureAdvanced': 'Advanced feature 5',
    '6featureAdvanced': 'Advanced feature 6',
    '7featureAdvanced': 'Advanced feature 7',
    '8featureAdvanced': 'Advanced feature 8',
    '9featureAdvanced': 'Advanced feature 9',
    '10featureAdvanced': 'Advanced feature 10',
    '1featureEnterprise': 'Enterprise feature 1',
    '2featureEnterprise': 'Enterprise feature 2',
    '3featureEnterprise': 'Enterprise feature 3',
    '4featureEnterprise': 'Enterprise feature 4',
    '5featureEnterprise': 'Enterprise feature 5',
    '6featureEnterprise': 'Enterprise feature 6',
    '7featureEnterprise': 'Enterprise feature 7',
    '8featureEnterprise': 'Enterprise feature 8',
    '9featureEnterprise': 'Enterprise feature 9',
    '10featureEnterprise': 'Enterprise feature 10',
  },
};

const meta: Meta<typeof MainLanding> = {
  title: 'Organisms/Landing/MainLanding',
  component: MainLanding,
};
export default meta;

type Story = StoryObj<typeof MainLanding>;

export const Default: Story = {
  render: () => (
    <NextIntlClientProvider locale="en" messages={{ ...messages }}>
      <MainLanding />
    </NextIntlClientProvider>
  ),
};
