query findWarehouseById($id: ID!) {
  getWarehouseById(id: $id) {
    id
    name
    stockPerWarehouses {
      id
      warehouseId
      qtyAvailable
      qtyReserved
      lotNumber
      serialNumbers
      productLocation
      estimatedReplenishmentDate
      variantSku
      variantFirstAttribute {
        key
        value
      }
      productName
    }
  }
}

query findInventory(
  $page: Int = 1
  $limit: Int = 10
  $addressId: ID
  $variantId: ID
  $isArchived: Boolean
  $lowStockThreshold: Int
  $sortBy: SortBy
  $sortOrder: SortOrder
) {
  getAllWarehouses(
    page: $page
    limit: $limit
    addressId: $addressId
    variantId: $variantId
    isArchived: $isArchived
    lowStockThreshold: $lowStockThreshold
    sortBy: $sortBy
    sortOrder: $sortOrder
  ) {
    warehouses {
      id
      name
      stockPerWarehouses {
        id
        productLocation
        qtyAvailable
        lotNumber
        qtyReserved
        estimatedReplenishmentDate
        serialNumbers
        variantFirstAttribute {
          key
          value
        }
        productName
        variantSku
      }
    }
    total
    hasMore
  }
}

query findWarehouses(
  $page: Int = 1
  $limit: Int = 10
  $name: String
  $addressId: ID
  $sortBy: SortBy
  $sortOrder: SortOrder
) {
  getAllWarehouses(
    page: $page
    limit: $limit
    name: $name
    addressId: $addressId
    sortBy: $sortBy
    sortOrder: $sortOrder
    includeAddresses: true
  ) {
    warehouses {
      id
      name
      addressId
      addressLine1
      city
      countryCode
      postalCode
    }
    total
    hasMore
  }
}
