query findWarehouseById($id: ID!) {
  getWarehouseById(id: $id) {
    id
    name
    stockPerWarehouses {
      id
      warehouseId
      qtyAvailable
      qtyReserved
      lotNumber
      serialNumbers
      productLocation
      estimatedReplenishmentDate
      variantSku
      variantFirstAttribute {
        key
        value
      }
      productName
    }
  }
}

query findInventory(
  $page: Int = 1
  $limit: Int = 10
  $name: String
  $addressId: ID
  $sortBy: SortBy
  $sortOrder: SortOrder
  $includeAddresses: Boolean = true
  $filters: StockPerWarehouseFilterInput
  $search: String
) {
  getAllWarehouses(
    page: $page
    limit: $limit
    name: $name
    addressId: $addressId
    sortBy: $sortBy
    sortOrder: $sortOrder
    includeAddresses: $includeAddresses
    filters: $filters
    search: $search
  ) {
    warehouses {
      id
      name
      createdAt
      updatedAt
      addressId
      addressLine1
      city
      countryCode
      postalCode
      stockPerWarehouses {
        id
        qtyAvailable
        qtyReserved
        lotNumber
        serialNumbers
        productLocation
        estimatedReplenishmentDate
        variantId
        variantSku
        productName
        variantFirstAttribute {
          key
          value
        }
      }
    }
    total
    hasMore
  }
}

query findWarehouses(
  $page: Int = 1
  $limit: Int = 10
  $name: String
  $addressId: ID
  $sortBy: SortBy
  $sortOrder: SortOrder
) {
  getAllWarehouses(
    page: $page
    limit: $limit
    name: $name
    addressId: $addressId
    sortBy: $sortBy
    sortOrder: $sortOrder
    includeAddresses: true
  ) {
    warehouses {
      id
      name
      addressId
      addressLine1
      city
      countryCode
      postalCode
    }
    total
    hasMore
  }
}
