mutation register($email: String!, $password: String!, $accountType: AccountTypeEnum!) {
  register(input: {
    email: $email,
    password: $password,
    accountType: $accountType
  }) {
    email
    accountType
  }
}

mutation login($email: String!, $password: String!, $accountType: AccountTypeEnum!) {
  login(input: {
    email: $email,
    password: $password,
    accountType: $accountType
  }) {
    success
    message
  }
}

mutation logout {
  logout {
    success
    message
  }
}

