mutation register($email: String!, $password: String!, $accountType: AccountTypeEnum!) {
  register(input: {
    email: $email,
    password: $password,
    accountType: $accountType
  }) {
    email
    accountType
  }
}

mutation login($email: String!, $password: String!, $accountType: AccountTypeEnum!) {
  login(input: {
    email: $email,
    password: $password,
    accountType: $accountType
  }) {
    success
    message
  }
}

mutation logout {
  logout {
    success
    message
  }
}

mutation getInTouch(
  $fullName: String!
  $businessEmail: String!
  $businessPhone: String!
  $company: String!
  $websiteUrl: String!
  $country: String!
  $annualRevenue: String!
  $isAgency: String!
) {
  getInTouch(input: {
    fullName: $fullName
    businessEmail: $businessEmail
    businessPhone: $businessPhone
    company: $company
    websiteUrl: $websiteUrl
    country: $country
    annualRevenue: $annualRevenue
    isAgency: $isAgency
  }) {
    success
    message
  }
}
