mutation register($email: String!, $password: String!, $accountType: AccountTypeEnum!) {
  register(input: {
    email: $email,
    password: $password,
    accountType: $accountType
  }) {
    email
    accountType
  }
}

mutation login($email: String!, $password: String!, $accountType: AccountTypeEnum!) {
  login(input: {
    email: $email,
    password: $password,
    accountType: $accountType
  }) {
    success
    message
  }
}

mutation forgotPassword($email: String!, $accountType: AccountTypeEnum!) {
  forgotPassword(input: {
    email: $email,
    accountType: $accountType
  }) {
    success
    message
  }
}

mutation updatePassword($token: String!, $password: String!) {
  updatePassword(input: {    
    token: $token
    password: $password,
  }) {
    success
    message
  }
}

mutation logout {
  logout {
    success
    message
  }
}

