mutation archiveVariantOfProduct($id: String!, $productId: String!) {
  archiveVariant(id: $id, productId: $productId) {
    variants {
      isArchived
    }
  }
}

mutation restoreVariantOfProduct($id: String!, $productId: String!) {
  restoreVariant(id: $id, productId: $productId) {
    variants {
      isArchived
    }
  }
}

mutation removeVariantfromProduct($id: String!, $productId: String!) {
  removeVariant(id: $id, productId: $productId) {
    variants {
      sku
    }
  }
}
