query findCategoryById($id: ID!) {
  getCategoryById(id: $id) {
    id
    name
    description
    cover
    updatedAt
    createdAt
    subCategories {
      id
      name
      description
      cover
    }
  }
}

query findAllCategories(
  $page: Int = 1
  $limit: Int = 25
  $name: String = ""
  $parentId: ID = null
  $sortBy: SortBy = NAME
  $sortOrder: SortOrder = ASC
  $includeSubcategories: Boolean = false
) {
  getAllCategories(
    page: $page
    limit: $limit
    name: $name
    parentId: $parentId
    sortBy: $sortBy
    sortOrder: $sortOrder
    includeSubcategories: $includeSubcategories
  ) {
    categories {
      id
      name
      description
      cover
      updatedAt
      createdAt
      parentId
      subCategories {
        id
        parentId
        name
        description
        cover
        createdAt
        updatedAt
      }
    }
    total
    hasMore
  }
}

query findCategoriesTree($sortBy: SortBy = NAME, $sortOrder: SortOrder = ASC) {
  getAllCategories(sortBy: $sortBy, sortOrder: $sortOrder) {
    categories {
      id
      name
      parentId
      subCategories {
        id
        parentId
        name
        subCategories {
          id
          parentId
          name
          subCategories {
            id
            parentId
            name
            subCategories {
              id
              parentId
              name
              subCategories {
                id
                parentId
                name
                subCategories {
                  id
                  parentId
                  name
                  subCategories {
                    id
                    parentId
                    name
                    subCategories {
                      id
                      parentId
                      name
                      subCategories {
                        id
                        parentId
                        name
                        subCategories {
                          id
                          parentId
                          name
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
