query findCategoryById($id: ID!) {
  getCategoryById(id: $id) {
    name
    description
    cover
    updatedAt
    createdAt
    subCategories {
      name
      description
      cover
      createdAt
      subCategories {
        name
        description
        cover
        createdAt
        subCategories {
          cover
          createdAt
          description
          name
          updatedAt
        }
        updatedAt
      }
      updatedAt
    }
  }
}

query findAllCategories(

  $page: Int = 1
  $limit: Int = 25
  $name: String = ""
  $parentId: ID = ""
  $sortBy: SortBy = CREATED_AT
  $sortOrder: SortOrder = DESC
) {
  getAllCategories(
    page: $page
    limit: $limit
    name: $name
    parentId: $parentId
    sortBy: $sortBy
    sortOrder: $sortOrder
  ) {
    categories {
      name
      description
      cover
      updatedAt
      createdAt
      subCategories {
        name
        description
        cover
        createdAt
        subCategories {
          name
          description
          cover
          createdAt
          subCategories {
            cover
            createdAt
            description
            name
            updatedAt
          }
          updatedAt
        }
        updatedAt
      }
    }
    total
    hasMore
  }
}
