mutation createProduct($input: CreateProductInput!) {
  createProduct(input: $input) {
    name
    shortDescription
    longDescription
    productType
    cover
    tags
    brand
    manufacturer
    variants {
      attributes {
        key
        value
      }
      price
      weight
      variantCover
      upc
      sku
      personalizationOptions
      isbn
      installmentPayments {
        months
        interestRate
      }
      ean
      dimension {
        width
        length
        height
      }
      condition
      barcode
      warranties {
        instructions
        months
        coverage
      }
      variantMedia {
        variantId
        url
        productId
        position
        mediaType
      }
    }
    createdAt
    updatedAt
    sustainabilities {
      recycledPercentage
      certification
    }
    isArchived
    media {
      url
      productId
      position
      mediaType
      variantId
    }
    categories {
      categoryId
      categoryName
      categoryDescription
      categoryCover
    }
  }
}

mutation update($id: String!, $input: UpdateProductInput!) {
  updateProduct(id: $id, input: $input) {
    id
    brand
    categories {
      categoryId
      categoryName
      categoryDescription
      categoryCover
    }
    cover
    createdAt
    isArchived
    longDescription
    manufacturer
    media {
      mediaType
      position
      productId
      url
      variantId
    }
    name
    productType
    shortDescription
    sustainabilities {
      certification
      recycledPercentage
    }
    tags
    updatedAt
    variants {
      id
      attributes {
        key
        value
      }
      barcode
      condition
      dimension {
        height
        length
        width
      }
      ean
      installmentPayments {
        interestRate
        months
      }
      isbn
      personalizationOptions
      price
      sku
      upc
      variantCover
      variantMedia {
        mediaType
        position
        productId
        url
        variantId
      }
      warranties {
        coverage
        instructions
        months
      }
      weight
      isArchived
    }
  }
}

mutation softDelete($id: String!) {
  softDeleteProduct(id: $id) {
    name
    isArchived
  }
}

mutation restore($id: String!) {
  restoreProduct(id: $id) {
    name
    isArchived
  }
}

mutation hardDelete($id: String!) {
  hardDeleteProduct(id: $id) {
    name
  }
}
