services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    # Enabling Next.js development mode
    stdin_open: true
    tty: true
    command: npm run dev
